const arrayButtons = [
  {
    text: { en: '`', ru: 'ё' },
    wide: 'normal',
    altText: { en: '~', ru: 'ё' },
    br: false,
    type: 'alternative',
    code: 'Backquote',
  },
  {
    text: { en: '1', ru: '1' },
    wide: 'normal',
    altText: { en: '!', ru: '!' },
    br: false,
    type: 'alternative',
    code: 'Digit1',
  },
  {
    text: { en: '2', ru: '2' },
    wide: 'normal',
    altText: { en: '@', ru: '"' },
    br: false,
    type: 'alternative',
    code: 'Digit2',
  },
  {
    text: { en: '3', ru: '3' },
    wide: 'normal',
    altText: { en: '#', ru: '№' },
    br: false,
    type: 'alternative',
    code: 'Digit3',
  },
  {
    text: { en: '4', ru: '4' },
    wide: 'normal',
    altText: { en: '$', ru: ';' },
    br: false,
    type: 'alternative',
    code: 'Digit4',
  },
  {
    text: { en: '5', ru: '5' },
    wide: 'normal',
    altText: { en: '%', ru: '%' },
    br: false,
    type: 'alternative',
    code: 'Digit5',
  },
  {
    text: { en: '6', ru: '6' },
    wide: 'normal',
    altText: { en: '^', ru: ':' },
    br: false,
    type: 'alternative',
    code: 'Digit6',
  },
  {
    text: { en: '7', ru: '7' },
    wide: 'normal',
    altText: { en: '&', ru: '?' },
    br: false,
    type: 'alternative',
    code: 'Digit7',
  },
  {
    text: { en: '8', ru: '8' },
    wide: 'normal',
    altText: { en: '*', ru: '*' },
    br: false,
    type: 'alternative',
    code: 'Digit8',
  },
  {
    text: { en: '9', ru: '9' },
    wide: 'normal',
    altText: { en: '(', ru: '(' },
    br: false,
    type: 'alternative',
    code: 'Digit9',
  },
  {
    text: { en: '0', ru: '0' },
    wide: 'normal',
    altText: { en: ')', ru: ')' },
    br: false,
    type: 'alternative',
    code: 'Digit0',
  },
  {
    text: { en: '-', ru: '-' },
    wide: 'normal',
    altText: { en: '_', ru: '_' },
    br: false,
    type: 'alternative',
    code: 'Minus',
  },
  {
    text: { en: '=', ru: '=' },
    wide: 'normal',
    altText: { en: '+', ru: '+' },
    br: false,
    type: 'alternative',
    code: 'Equal',
  },
  {
    text: { en: 'Backspace', ru: 'Backspace' },
    wide: 'middle-wide',
    altText: { en: 'Backspace', ru: 'Backspace' },
    br: true,
    type: 'functional',
    code: 'Backspace',
  },
  {
    text: { en: 'Tab', ru: 'Tab' },
    wide: 'normal',
    altText: { en: 'Tab', ru: 'Tab' },
    br: false,
    type: 'functional',
    code: 'Tab',
  },
  {
    text: { en: 'q', ru: 'й' },
    wide: 'normal',
    altText: { en: 'q', ru: 'й' },
    br: false,
    type: 'word',
    code: 'KeyQ',
  },
  {
    text: { en: 'w', ru: 'ц' },
    wide: 'normal',
    altText: { en: 'w', ru: 'ц' },
    br: false,
    type: 'word',
    code: 'KeyW',
  },
  {
    text: { en: 'e', ru: 'у' },
    wide: 'normal',
    altText: { en: 'e', ru: 'у' },
    br: false,
    type: 'word',
    code: 'KeyE',
  },
  {
    text: { en: 'r', ru: 'к' },
    wide: 'normal',
    altText: { en: 'r', ru: 'к' },
    br: false,
    type: 'word',
    code: 'KeyR',
  },
  {
    text: { en: 't', ru: 'е' },
    wide: 'normal',
    altText: { en: 't', ru: 'е' },
    br: false,
    type: 'word',
    code: 'KeyT',
  },
  {
    text: { en: 'y', ru: 'н' },
    wide: 'normal',
    altText: { en: 'y', ru: 'н' },
    br: false,
    type: 'word',
    code: 'KeyY',
  },
  {
    text: { en: 'u', ru: 'г' },
    wide: 'normal',
    altText: { en: 'u', ru: 'г' },
    br: false,
    type: 'word',
    code: 'KeyU',
  },
  {
    text: { en: 'i', ru: 'ш' },
    wide: 'normal',
    altText: { en: 'i', ru: 'ш' },
    br: false,
    type: 'word',
    code: 'KeyI',
  },
  {
    text: { en: 'o', ru: 'щ' },
    wide: 'normal',
    altText: { en: 'o', ru: 'щ' },
    br: false,
    type: 'word',
    code: 'KeyO',
  },
  {
    text: { en: 'p', ru: 'з' },
    wide: 'normal',
    altText: { en: 'p', ru: 'з' },
    br: false,
    type: 'word',
    code: 'KeyP',
  },
  {
    text: { en: '[', ru: 'х' },
    wide: 'normal',
    altText: { en: '{', ru: 'х' },
    br: false,
    type: 'alternative',
    code: 'BracketLeft',
  },
  {
    text: { en: ']', ru: 'ъ' },
    wide: 'normal',
    altText: { en: '}', ru: 'ъ' },
    br: false,
    type: 'alternative',
    code: 'BracketRight',
  },
  {
    text: { en: '\\', ru: '\\' },
    wide: 'wide',
    altText: { en: '|', ru: '/' },
    br: false,
    type: 'alternative',
    code: 'Backslash',
  },
  {
    text: { en: 'DEL', ru: 'DEL' },
    wide: 'normal',
    altText: { en: 'DEL', ru: 'DEL' },
    br: true,
    type: 'functional',
    code: 'Delete',
  },
  {
    text: { en: 'Caps Lock', ru: 'Caps Lock' },
    wide: 'wide',
    altText: { en: 'Caps Lock', ru: 'Caps Lock' },
    br: false,
    type: 'functional',
    code: 'CapsLock',
  },
  {
    text: { en: 'a', ru: 'ф' },
    wide: 'normal',
    altText: { en: 'a', ru: 'ф' },
    br: false,
    type: 'word',
    code: 'KeyA',
  },
  {
    text: { en: 's', ru: 'ы' },
    wide: 'normal',
    altText: { en: 's', ru: 'ы' },
    br: false,
    type: 'word',
    code: 'KeyS',
  },
  {
    text: { en: 'd', ru: 'в' },
    wide: 'normal',
    altText: { en: 'd', ru: 'в' },
    br: false,
    type: 'word',
    code: 'KeyD',
  },
  {
    text: { en: 'f', ru: 'а' },
    wide: 'normal',
    altText: { en: 'f', ru: 'а' },
    br: false,
    type: 'word',
    code: 'KeyF',
  },
  {
    text: { en: 'g', ru: 'п' },
    wide: 'normal',
    altText: { en: 'g', ru: 'п' },
    br: false,
    type: 'word',
    code: 'KeyG',
  },
  {
    text: { en: 'h', ru: 'р' },
    wide: 'normal',
    altText: { en: 'h', ru: 'р' },
    br: false,
    type: 'word',
    code: 'KeyH',
  },
  {
    text: { en: 'j', ru: 'о' },
    wide: 'normal',
    altText: { en: 'j', ru: 'о' },
    br: false,
    type: 'word',
    code: 'KeyJ',
  },
  {
    text: { en: 'k', ru: 'л' },
    wide: 'normal',
    altText: { en: 'k', ru: 'л' },
    br: false,
    type: 'word',
    code: 'KeyK',
  },
  {
    text: { en: 'l', ru: 'д' },
    wide: 'normal',
    altText: { en: 'l', ru: 'д' },
    br: false,
    type: 'word',
    code: 'KeyL',
  },
  {
    text: { en: ';', ru: 'ж' },
    wide: 'normal',
    altText: { en: ':', ru: 'ж' },
    br: false,
    type: 'alternative',
    code: 'Semicolon',
  },
  {
    text: { en: `'`, ru: 'э' },
    wide: 'normal',
    altText: { en: '"', ru: 'э' },
    br: false,
    type: 'alternative',
    code: 'Quote',
  },
  {
    text: { en: 'ENTER', ru: 'ENTER' },
    wide: 'middle-wide',
    altText: { en: 'ENTER', ru: 'ENTER' },
    br: true,
    type: 'functional',
    code: 'Enter',
  },
  {
    text: { en: 'Shift', ru: 'Shift' },
    wide: 'middle-wide',
    altText: { en: 'Shift', ru: 'Shift' },
    br: false,
    type: 'functional',
    code: 'ShiftLeft',
  },
  {
    text: { en: 'z', ru: 'я' },
    wide: 'normal',
    altText: { en: 'z', ru: 'я' },
    br: false,
    type: 'word',
    code: 'KeyZ',
  },
  {
    text: { en: 'x', ru: 'ч' },
    wide: 'normal',
    altText: { en: 'x', ru: 'ч' },
    br: false,
    type: 'word',
    code: 'KeyX',
  },
  {
    text: { en: 'c', ru: 'с' },
    wide: 'normal',
    altText: { en: 'c', ru: 'с' },
    br: false,
    type: 'word',
    code: 'KeyC',
  },
  {
    text: { en: 'v', ru: 'м' },
    wide: 'normal',
    altText: { en: 'v', ru: 'м' },
    br: false,
    type: 'word',
    code: 'KeyV',
  },
  {
    text: { en: 'b', ru: 'и' },
    wide: 'normal',
    altText: { en: 'b', ru: 'и' },
    br: false,
    type: 'word',
    code: 'KeyB',
  },
  {
    text: { en: 'n', ru: 'т' },
    wide: 'normal',
    altText: { en: 'n', ru: 'т' },
    br: false,
    type: 'word',
    code: 'KeyN',
  },
  {
    text: { en: 'm', ru: 'ь' },
    wide: 'normal',
    altText: { en: 'm', ru: 'ь' },
    br: false,
    type: 'word',
    code: 'KeyM',
  },
  {
    text: { en: ',', ru: 'б' },
    wide: 'normal',
    altText: { en: '<', ru: 'б' },
    br: false,
    type: 'alternative',
    code: 'Comma',
  },
  {
    text: { en: '.', ru: 'ю' },
    wide: 'normal',
    altText: { en: '>', ru: 'ю' },
    br: false,
    type: 'alternative',
    code: 'Period',
  },
  {
    text: { en: '/', ru: '.' },
    wide: 'normal',
    altText: { en: '?', ru: ',' },
    br: false,
    type: 'alternative',
    code: 'Slash',
  },
  {
    text: { en: '&#8593;', ru: '&#8593;' },
    wide: 'normal',
    altText: { en: '&#8593;', ru: '&#8593;' },
    br: false,
    type: 'functional',
    code: 'ArrowUp',
  },
  {
    text: { en: 'Shift', ru: 'Shift' },
    wide: 'middle-wide',
    altText: { en: 'Shift', ru: 'Shift' },
    br: true,
    type: 'functional',
    code: 'ShiftRight',
  },
  {
    text: { en: 'Ctrl', ru: 'Ctrl' },
    wide: 'wide',
    altText: { en: 'Ctrl', ru: 'Ctrl' },
    br: false,
    type: 'functional',
    code: 'ControlLeft',
  },
  {
    text: { en: 'Win', ru: 'Win' },
    wide: 'wide',
    altText: { en: 'Win', ru: 'Win' },
    br: false,
    type: 'functional',
    code: 'OSLeft',
  },
  {
    text: { en: 'Alt', ru: 'Alt' },
    wide: 'wide',
    altText: { en: 'Alt', ru: 'Alt' },
    br: false,
    type: 'functional',
    code: 'AltLeft',
  },
  {
    text: { en: ' ', ru: ' ' },
    wide: 'ultra-wide',
    altText: { en: ' ', ru: ' ' },
    br: false,
    type: 'word',
    code: 'Space',
  },
  {
    text: { en: 'Alt', ru: 'Alt' },
    wide: 'wide',
    altText: { en: 'Alt', ru: 'Alt' },
    br: false,
    type: 'functional',
    code: 'AltRight',
  },
  {
    text: { en: '&#8592;', ru: '&#8592;' },
    wide: 'normal',
    altText: { en: '&#8592;', ru: '&#8592;' },
    br: false,
    type: 'functional',
    code: 'ArrowLeft',
  },
  {
    text: { en: '&#8595;', ru: '&#8595;' },
    wide: 'normal',
    altText: { en: '&#8595;', ru: '&#8595;' },
    br: false,
    type: 'functional',
    code: 'ArrowDown',
  },
  {
    text: { en: '&#8594;', ru: '&#8594;' },
    wide: 'normal',
    altText: { en: '&#8594;', ru: '&#8594;' },
    br: false,
    type: 'functional',
    code: 'ArrowRight',
  },
  {
    text: { en: 'Ctrl', ru: 'Ctrl' },
    wide: 'wide',
    altText: { en: 'Ctrl', ru: 'Ctrl' },
    br: true,
    type: 'functional',
    code: 'ControlRight',
  },
];

export default arrayButtons;
